### ISSUE TITLE
Add Random Passwd

### ISSUE THREAD

**Issue by connor557** [kxes/docker-kxdesktop#1]
I'm using this system for a VDI deployment w/ docker and I don't know the rott password or non-privliged user either for that matter.

**Comment by joshiggins** [comment]
I just checked your fork and it looks like you got it

```
RUN echo "root:newpassword" | chpasswd
```

or to add a non-privileged user you should add it first

```
RUN useradd josh
RUN echo "josh:newpassword" | chpasswd

**Comment by joshiggins** [comment]
closed by accident but feel free to re-open.
